name: run-tests
run-name: Run tests
on:
  - push
jobs:
  run-tests:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-testbuildjet
          restore-keys: |
            ${{ runner.os }}-golang-
      - run: go test .
